### ISSUE TITLE
Readme Demo Config Error

### ISSUE THREAD

**Issue by crystalGS** [eggjs/egg-session-redis#2]
When i use the following config : 

```
exports.redis = {
  clients: {
    session: { /* config */ },
    cache: { /* config */ },
  },
};
```

I got an Error

```
AssertionError: [egg-redis] 'host: undefined', 'port: undefined', 'password: undefined', 'db: undefined' are required on config
```

It doesn't work when i use `clients`. Maybe it should be used by `client`?

I change it  and then it work

**Comment by dead-horse** [comment]
I'll add a example with only one redis instance

**Comment by dead-horse** [comment]
closes via https://github.com/eggjs/egg-session-redis/commit/be4178ac3a8c1e8e3ba38f6ba5cb5080870132e4

**Comment by atian25** [comment]
next time, report at https://github.com/eggjs/egg/issues
